// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy6ey5ePk7s6BA5lXt5yeUGwwB8whKs8c',
    appId: '1:325480975565:web:5c9e34a7c1918de2f6ed84',
    messagingSenderId: '325480975565',
    projectId: 'reent-app',
    authDomain: 'reent-app.firebaseapp.com',
    storageBucket: 'reent-app.firebasestorage.app',
    measurementId: 'G-EMGQT755Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ZlSetwFrX2MwwNM9sfPk7K3vzHQandc',
    appId: '1:325480975565:android:69fab055c052d6a5f6ed84',
    messagingSenderId: '325480975565',
    projectId: 'reent-app',
    storageBucket: 'reent-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsfJivmxYaT2yxoIz4FWRY2RTuPx1oQA',
    appId: '1:325480975565:ios:08823e33d0c2f967f6ed84',
    messagingSenderId: '325480975565',
    projectId: 'reent-app',
    storageBucket: 'reent-app.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpsfJivmxYaT2yxoIz4FWRY2RTuPx1oQA',
    appId: '1:325480975565:ios:08823e33d0c2f967f6ed84',
    messagingSenderId: '325480975565',
    projectId: 'reent-app',
    storageBucket: 'reent-app.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy6ey5ePk7s6BA5lXt5yeUGwwB8whKs8c',
    appId: '1:325480975565:web:598976118191d6aef6ed84',
    messagingSenderId: '325480975565',
    projectId: 'reent-app',
    authDomain: 'reent-app.firebaseapp.com',
    storageBucket: 'reent-app.firebasestorage.app',
    measurementId: 'G-E0W8ECV6DS',
  );
}
